version: '3.8'
services:

  wordservice:
    build: ./WordService
    ports:
      - "5000:8080" 
    networks:
      - wordservice_network

  wordservice-dapr: 
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: [
      "./daprd",
      "--app-id", "wordservice",
      "--app-port", "8080",
      "--dapr-http-port", "3500",
      "--dapr-grpc-port", "50001",
      "--components-path", "/components"
    ]
    volumes:
      - "./components:/components"
    depends_on:
      - wordservice
    network_mode: "service:wordservice"

networks:
  wordservice_network:
    driver: bridge